config/routes.rb
SakshumApp::Application.routes.draw do
  resources :blood_donors

end

app/models/blood_donor.rb
class BloodDonor < ActiveRecord::Base
  attr_accessible :bloodGroup, :city, :email, :gender, :name, :state, :zip
  validates :name, :length => { :maximum => 30 }
  validates :zip, :length => { :maximum => 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blood_donors_controller.rb
class BloodDonorsController < ApplicationController
  # GET /blood_donors
  # GET /blood_donors.json
  def index
    @blood_donors = BloodDonor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blood_donors }
    end
  end

  # GET /blood_donors/1
  # GET /blood_donors/1.json
  def show
    @blood_donor = BloodDonor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blood_donor }
    end
  end

  # GET /blood_donors/new
  # GET /blood_donors/new.json
  def new
    @blood_donor = BloodDonor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blood_donor }
    end
  end

  # GET /blood_donors/1/edit
  def edit
    @blood_donor = BloodDonor.find(params[:id])
  end

  # POST /blood_donors
  # POST /blood_donors.json
  def create
    @blood_donor = BloodDonor.new(params[:blood_donor])

    respond_to do |format|
      if @blood_donor.save
        format.html { redirect_to @blood_donor, notice: 'Blood donor was successfully created.' }
        format.json { render json: @blood_donor, status: :created, location: @blood_donor }
      else
        format.html { render action: "new" }
        format.json { render json: @blood_donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blood_donors/1
  # PUT /blood_donors/1.json
  def update
    @blood_donor = BloodDonor.find(params[:id])

    respond_to do |format|
      if @blood_donor.update_attributes(params[:blood_donor])
        format.html { redirect_to @blood_donor, notice: 'Blood donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blood_donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_donors/1
  # DELETE /blood_donors/1.json
  def destroy
    @blood_donor = BloodDonor.find(params[:id])
    @blood_donor.destroy

    respond_to do |format|
      format.html { redirect_to blood_donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blood_donors_helper.rb
module BloodDonorsHelper
end

app/views/blood_donors/_form.html.erb
<%= form_for(@blood_donor) do |f| %>
  <% if @blood_donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood_donor.errors.count, "error") %> prohibited this blood_donor from being saved:</h2>

      <ul>
      <% @blood_donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :bloodGroup %><br />
    <%= f.text_field :bloodGroup %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blood_donors/edit.html.erb
<h1>Editing blood_donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @blood_donor %> |
<%= link_to 'Back', blood_donors_path %>

app/views/blood_donors/index.html.erb
<h1>Listing blood_donors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Bloodgroup</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blood_donors.each do |blood_donor| %>
  <tr>
    <td><%= blood_donor.name %></td>
    <td><%= blood_donor.email %></td>
    <td><%= blood_donor.gender %></td>
    <td><%= blood_donor.bloodGroup %></td>
    <td><%= blood_donor.city %></td>
    <td><%= blood_donor.state %></td>
    <td><%= blood_donor.zip %></td>
    <td><%= link_to 'Show', blood_donor %></td>
    <td><%= link_to 'Edit', edit_blood_donor_path(blood_donor) %></td>
    <td><%= link_to 'Destroy', blood_donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blood donor', new_blood_donor_path %>

app/views/blood_donors/new.html.erb
<h1>New blood_donor</h1>

<%= render 'form' %>

<%= link_to 'Back', blood_donors_path %>

app/views/blood_donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blood_donor.name %>
</p>

<p>
  <b>Email:</b>
  <%= @blood_donor.email %>
</p>

<p>
  <b>Gender:</b>
  <%= @blood_donor.gender %>
</p>

<p>
  <b>Bloodgroup:</b>
  <%= @blood_donor.bloodGroup %>
</p>

<p>
  <b>City:</b>
  <%= @blood_donor.city %>
</p>

<p>
  <b>State:</b>
  <%= @blood_donor.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @blood_donor.zip %>
</p>


<%= link_to 'Edit', edit_blood_donor_path(@blood_donor) %> |
<%= link_to 'Back', blood_donors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SakshumApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>